### PR TITLE
Handle reuse of sftp node for further actions

### PR DESCRIPTION
**Pull request by sahaine**

### CODE REVIEW

**Comment by zagi988** [comment]
@fatoldsun00 could you please merge this so this finally gets resolved? It's a very annoying error on otherwise very useful node.

**Comment by fatoldsun00** [comment]
Hi,
Done

**Comment by zagi988** [comment]
Can you also go on npm and request an update so it pulls the latest version from here?

**Comment by fatoldsun00** [comment]
It's done,

I can change ownership, if someone want to maintain this repo

**Pull request merged**
